export const CONTEST_READ_REPOSITORY = 'CONTEST_READ_REPOSITORY';

export const CONTEST_WRITE_REPOSITORY = 'CONTEST_WRITE_REPOSITORY';

export const CONTEST_PARTICIPATE_READ_REPOSITORY =
  'CONTEST_PARTICIPATE_READ_REPOSITORY';

export const CONTEST_PARTICIPATE_WRITE_REPOSITORY =
  'CONTEST_PARTICIPATE_WRITE_REPOSITORY';

export const CONTEST_WINNER_READ_REPOSITORY = 'CONTEST_WINNER_READ_REPOSITORY';

export const CONTEST_WINNER_WRITE_REPOSITORY =
  'CONTEST_WINNER_WRITE_REPOSITORY';

export const CHANNEL_READ_REPOSITORY = 'CHANNEL_READ_REPOSITORY';

export const CHANNEL_WRITE_REPOSITORY = 'CHANNEL_WRITE_REPOSITORY';
