// Фаза 9: единый репозиторий на агрегат (токен+интерфейс).
export const USER_REPOSITORY = 'USER_REPOSITORY';

export const CHANNEL_REPOSITORY = 'CHANNEL_REPOSITORY';

export const CONTEST_REPOSITORY = 'CONTEST_REPOSITORY';

export const CONTEST_PARTICIPATE_REPOSITORY = 'CONTEST_PARTICIPATE_REPOSITORY';

export const CONTEST_WINNER_REPOSITORY = 'CONTEST_WINNER_REPOSITORY';
